#!/usr/bin/env bash

getInput -exzcwjg -q 120 -u 1 -v 0.75 -r 5 -f 1 -i /beevol/home/liggettl/sequencingData/7.11.19/unzipped_other_mouse -o /beevol/home/liggettl/sequencingData/7.11.19/results -b 'freebayes' -y '/beevol/home/liggettl/refgenomes/mouse/mm10.fa' -n 'Initial run of the dataset.'
